.Dd Jan 5, 2026
.Dt GIT-GRAB 1
.Os
.Sh NAME
.Nm git-grab
.Nd clone git repositories to a standard location
.Sh SYNOPSIS
.Nm
.Op Fl chnpV
.Ar URL No ...
.Op Ar -- git arguments No ...
.Sh DESCRIPTION
The
.Nm
utility clones git repositories to a standard location based on the repository URL.
Pass one or more
.Ar URL
to clone. Arguments for git may be supplied after
.Ar -- .
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl c, -clipboard
Paste a URL to clone from the clipboard.
.It Fl p, -copy-path
Copy the local destination path to clipboard after cloning.
.It Fl -pattern Ar PATTERN
Destination path pattern for grabbed repositories with optional placeholders.
Default is
.Pa ~/src/{host/}{owner/}{repo}
or
.Ev GRAB_PATTERN .
.Pp
Placeholders are enclosed in curly braces
.Li {}.
Optionally, they may have leading and trailing
.Li /
characters.
If the placeholder is present, the slashes will be added to the path, otherwise they will be omitted.
Placeholders can be escaped by doubling the curly braces, e.g.
.Li {{owner}}
will render as
.Li {owner} .
.Pp
The tilde
.Li ~
at the start of the pattern is expanded to the home directory.
.Pp
The following placeholders are supported:
.Bl -dash -compact
.It
.Li host
- the host part of the URL, e.g. github
.It
.Li owner
- the owner or organisation of the repo, e.g. wezm
.It
.Li repo
- the repository name, e.g. git-grab
.It
.Li home
- the user's home directory
.El
.Pp
Placeholders are case-sensitive, e.g.
.Li {Repo}
or
.Li {REPO}
is not valid.
.It Fl -home Ar DIR No (deprecated)
The
.Li ~
character or
.Li {home}
placeholder in the pattern expands to this directory.
Default is
.Ev GRAB_HOME .
.It Fl n, -dry-run
Don't clone repositories, but print what would be done.
.It Fl V, -version
Display version information and exit.
.El
.Sh ENVIRONMENT
.Bl -tag -width indent
.It Ev GRAB_PATTERN
See
.Fl -pattern .
.It Ev GRAB_COPY_PATH
If set, copy the local destination path to the clipboard after cloning.
(equivalent to
.Fl -copy-path )
.It Ev GRAB_HOME No (deprecated)
See
.Fl -home .
.El
.Sh EXIT STATUS
.Ex -std
.El
.Sh SEE ALSO
.Xr git-clone 1
.Sh HISTORY
The
.Nm
utility is inspired by grab by Jeff Hodges.
This implementation was written from scratch by Wesley Moore.
